### PR TITLE
updated timeline per IMSC 1.2 CR

### PR DESCRIPTION
**Pull request by himorin**

### CODE REVIEW

**Comment by himorin** [comment]
Actually future dates are mostly copied from timeline calculator, link in the PR: https://w3c.github.io/spec-releases/milestones/?cr=2020-03-24 , and I have no idea on that gap...
I've put brackets to ones which is not defined (from previous event) but something to be performed around the date...

**Comment by nigelmegitt** [comment]
Ah right, thanks, that makes sense. A small improvement would be to add that to the Notes at the top.

**Comment by himorin** [comment]
Considering automatically calculated and expected one (in milestones tool) exist, how about adding like this? (at abb4e88)

- Milestones which are automatically placed from previous event have yellow background.
- Dates, which do not have written definition of days from previous event in the Process but shown in milestones calculator (something of "expected" dates), are marked with blackets.

**Comment by nigelmegitt** [comment]
Hi @himorin hope you like the changes, I tried to make them a bit more consistent with https://www.w3.org/wiki/TimedText - feel free to change them again!

**Comment by himorin** [comment]
Thank you for your fix! I have no objection at all.
ok to merge with this?

**Pull request merged**
