### PR TITLE
fixed time (DST) for 2021/04/01

### PR DESCRIPTION
**Pull request by himorin**

### CODE REVIEW

**Review by gkatsev — APPROVED** [review]

**Comment by gkatsev** [comment]
On a separate note, should we try using https://www.w3.org/groups/wg/timed-text/calendar?

**Comment by himorin** [comment]
For group calendar at w3.org, I think someone already tried for TTWG (but already removed?)??
Both is ok for me, should be agenda+?

**Comment by gkatsev** [comment]
Specifically, was thinking of the new calendaring thing that's in beta.

**Comment by nigelmegitt** [comment]
> On a separate note, should we try using https://www.w3.org/groups/wg/timed-text/calendar?

I agree, we should use this instead of maintaining our own .ics files in the repo.

**Pull request merged**
