### PR TITLE
added spec timeline landing as immediate redirect

### PR DESCRIPTION
**Pull request by himorin**
from https://github.com/w3c/onboarding/pull/6, adding no-dated page for specification timeline with redirect (not a list of existing timelines).

### CODE REVIEW

**Review by nigelmegitt — COMMENTED** [review]
Out of interest, why do it this way rather than renaming the 2019 version to remove the date and adding a new redirect from the 2019 link to the undated one? If we did that then the new "canonical" link would be the undated one rather than the 2019 one.

**Comment by himorin** [comment]
oh, for dated file name, I've just followed previous one when I made it. If renaming with undated is ok, I'm really happy with that.

**Comment by nigelmegitt** [comment]
Yes, I think renaming with undated is better, probably.

**Comment by himorin** [comment]
> Yes, I think renaming with undated is better, probably.

modified this PR into just renaming timeline file.

**Review by nigelmegitt — APPROVED** [review]

**Comment by nigelmegitt** [comment]
Approved, I'm guessing you want to look after the timing of merging this @himorin if you're going to update and merge w3c/onboarding#6 as well?

**Comment by himorin** [comment]
> Approved, I'm guessing you want to look after the timing of merging this @himorin if you're going to update and merge [w3c/onboarding#6](https://github.com/w3c/onboarding/pull/6) as well?

Yes for onboarding one. For latter of my comment, I think I can update by myself. How about the first one?

**Comment by nigelmegitt** [comment]
Sorry @himorin I'm not sure which comment you mean. But I see that this PR doesn't create a redirect from the old dated spec timeline link to the new one - do you want to add that as well, so that if anyone has the old URL it continues to work?

**Comment by nigelmegitt** [comment]
I worked out which comment you meant @himorin and have resolved it, hopefully.

**Comment by himorin** [comment]
merging.

**Pull request merged**
